---
update_packages: true

switch_to_community_updates_repo: true
disable_no_subscription_prompt: true
install_pve_discord_dark_theme: true
enable_acme: false
install_nginx_proxy: true

managed_by_ansible_tag: managed_by_ansible

vm_iso_remove_unreferenced: true
ct_template_remove_unreferenced: true
vm_remove_unreferenced: true
container_remove_unreferenced: true

vm_restart_timeout: 240

vm_defaults_agent: true
vm_defaults_bios: seabios
vm_defaults_cores: 1
vm_defaults_cpu: host
vm_defaults_memory: 512
vm_defaults_onboot: false
vm_defaults_bootorder: false
vm_defaults_machine: q35
vm_defaults_ostype: l26
vm_defaults_scsihw: virtio-scsi-pci
vm_defaults_sockets: 1
vm_defaults_vga: qxl
vm_defaults_netdev_firewall: true
vm_defaults_netdev_type: virtio
vm_defaults_netdev_bridge: vmbr0

container_defaults:
  cores: 1
  memory: 512
  swap: 512
  nesting: true
  onboot: false
  unprivileged: true
  timezone: host
  start: false
  netdev_firewall: true
  nameserver: ""
  searchdomain: ""
