- name: Configure Proxmox to use ZFS pools
  when: storage_classes.zfs is defined and storage_classes.zfs is mapping
  delegate_to: "{{ groups['proxmox'] | sort | first }}"
  run_once: true
  block:
    - name: Get root password from Bitwarden # noqa: run-once[task]
      ansible.builtin.set_fact:
        root_password: "{{ lookup('community.general.bitwarden', 'proxmox_root', field='password')[0] }}"
      # no_log: true
      run_once: true

    - name: Get existing Proxmox storage
      community.general.proxmox_storage_info:
        api_host: "{{ ansible_host }}"
        api_user: root@pam
        api_password: "{{ root_password }}"
        api_token_id: "{{ token_id | default(omit) }}"
        api_token_secret: "{{ ansible_token_secret | default(omit) }}"
      register: proxmox_storages
      delegate_to: "localhost"

    - name: Add storage devices
      ansible.builtin.command: >
        pvesm add dir {{ item.value.name }} \
        --path /{{ item.value.name }}/ \
        --content {{ item.value.content }} --shared=1
      with_items: "{{ storage_classes.zfs | dict2items }}"
      when: item.value.name not in proxmox_storages.proxmox_storages | map(attribute='storage')
      changed_when: true

    - name: Update storage content types
      ansible.builtin.command: >
        pvesm set {{ item.value.name }} \
        --content {{ item.value.content }} --shared=1
      vars:
        current_supported_types: "{{ proxmox_storages.proxmox_storages | selectattr('storage', 'equalto', item.value.name) | \
          map(attribute='content') | flatten | sort }}"
        current_shared: "{{ proxmox_storages.proxmox_storages | selectattr('storage', 'equalto', item.value.name) | \
          map(attribute='shared') | first | default(0) }}"
        desired_types: "{{ item.value.content.split(',') | sort }}"
      when: >
        item.value.name in proxmox_storages.proxmox_storages | map(attribute='storage') and
        (current_supported_types != desired_types or current_shared != 1)
      with_items: "{{ storage_classes.zfs | dict2items }}"
      changed_when: true

    - name: Add ZFS storage device
      ansible.builtin.command: >
        pvesm add zfspool {{ item.value.name }}-zfs \
        --pool {{ item.value.name }}
      with_items: "{{ storage_classes.zfs | dict2items }}"
      when: item.value.name + '-zfs' not in proxmox_storages.proxmox_storages | map(attribute='storage')
      changed_when: true