---
- name: Update VM configuration VM-{{ vm.key }}
  vars:
    set_name: >-
      {{ ' --name "' + vm.value.name + '" '
      if vm.value.name | default('') | length > 0 and
      vm.value.name | default('') != vm_config.name | default('')
      else '' }}
    delete_name: >-
      {{ 'name,' if vm.value.name | default('') | length == 0 and
      vm_config.name | default('') | length > 0 else '' }}

    set_cores: >-
      {{ ' --cores ' + vm.value.cores | default(vm_defaults_cores) | string
      if vm.value.cores | default(vm_defaults_cores) != vm_config.cores | default(1) else '' }}

    set_cpu: >-
      {{ ' --cpu ' + vm.value.cpu | default(vm_defaults_cpu) | string
      if vm.value.cpu | default(vm_defaults_cpu) != vm_config.cpu | default(1) else '' }}

    set_sockets: >-
      {{ ' --sockets ' + vm.value.sockets | default(vm_defaults_sockets) | string
      if vm.value.sockets | default(vm_defaults_sockets) != vm_config.sockets | default(1) else '' }}

    set_memory: >-
      {{ ' --memory ' + vm.value.memory | default(vm_defaults_memory) | string
      if vm.value.memory | default(vm_defaults_memory) | int != vm_config.memory | default(512) | int else '' }}

    set_agent: >-
      {{ ' --agent ' + vm.value.agent | default(vm_defaults_agent) | ternary(1, 0) | string
      if vm.value.agent | default(vm_defaults_agent) | ternary('1', '0') != vm_config.agent | default('0') else '' }}

    set_onboot: >-
      {{ ' --onboot ' + vm.value.onboot | default(vm_defaults_onboot) | ternary(1, 0) | string
      if vm.value.onboot | default(vm_defaults_onboot) | ternary(1, 0) != vm_config.onboot | default(0) else '' }}

    set_scsihw: >-
      {{ ' --scsihw ' + vm.value.scsihw | default(vm_defaults_scsihw)
      if vm.value.scsihw | default(vm_defaults_scsihw) != vm_config.scsihw | default('') else '' }}

    vm_tags: "{{ (vm.value.tags | default([]) + [managed_by_ansible_tag]) | sort | join(';') }}"
    set_tags: "{{ ' --tags ' + vm_tags if vm_tags != '' and vm_tags != vm_config.tags | default('') else '' }}"

    set_vga: >-
      {{ ' --vga ' + vm.value.vga | default(vm_defaults_vga)
      if vm.value.vga | default(vm_defaults_vga) != vm_config.vga | default('') else '' }}

    set_ci_user: >-
      {{ ' --ciuser "' + vm.value.ci.user + '" '
      if vm.value.ci.user | default('') | length > 0 and
      vm.value.ci.user | default('') != vm_config.ciuser | default('')
      else '' }}
    delete_ci_user: >-
      {{ 'ciuser,' if vm.value.ci.user | default('') | length == 0 and
      vm_config.ciuser | default('') | length > 0 else '' }}

    set_ci_password: >-
      {{ ' --cipassword "' + vm.value.ci.password + '" '
      if vm.value.ci.password | default('') | length > 0 and
      (vm_config.cipassword | default('') | length == 0 or vm.value.ci.forcepassword | default(false))
      else '' }}
    delete_ci_password: >-
      {{ 'cipassword,' if vm.value.ci.password | default('') | length == 0 and
      vm_config.cipassword | default('') | length > 0 else '' }}

    set_ssh_keys: >-
      {{ ' --sshkeys "' + vm.value.ci.ssh_keys | urlencode | replace('/', '%2f') + '" '
      if vm.value.ci.ssh_keys | default('') | length > 0 and
      vm.value.ci.ssh_keys | default('') | urlencode | replace('/', '%2f') != vm_config.sshkeys | default('') | string
      else '' }}
    delete_ssh_keys: >-
      {{ 'sshkeys,' if vm.value.ci.ssh_keys | default('') | length == 0 and
      vm_config.sshkeys | string | default('') | length > 0 else '' }}

    set_nameserver: >-
      {{ ' --nameserver "' + vm.value.ci.nameserver + '" '
      if vm.value.ci.nameserver | default('') | length > 0 and
      vm.value.ci.nameserver | default('') != vm_config.nameserver | default('')
      else '' }}
    delete_nameserver: >-
      {{ 'nameserver,' if vm.value.ci.nameserver | default('') | length == 0 and
      vm_config.nameserver | default('') | length > 0 else '' }}

    set_searchdomain: >-
      {{ ' --searchdomain "' + vm.value.ci.searchdomain + '" '
      if vm.value.ci.searchdomain | default('') | length > 0 and
      vm.value.ci.searchdomain | default('') != vm_config.searchdomain | default('')
      else '' }}
    delete_searchdomain: >-
      {{ 'searchdomain,' if vm.value.ci.searchdomain | default('') | length == 0 and
      vm_config.searchdomain | default('') | length > 0 else '' }}

    to_delete: "\
      {{ delete_name }}\
      {{ delete_ci_user }}\
      {{ delete_ci_password }}\
      {{ delete_ssh_keys }}\
      {{ delete_nameserver }}\
      {{ delete_searchdomain }}"
    delete_cfg: "{{ ' --delete ' + to_delete if to_delete | trim != '' else '' }}"

    to_update: "\
      {{ set_name }}\
      {{ set_cores }}\
      {{ set_cpu }}\
      {{ set_sockets }}\
      {{ set_memory }}\
      {{ set_agent }}\
      {{ set_onboot }}\
      {{ set_scsihw }}\
      {{ set_ci_user }}\
      {{ set_ci_password }}\
      {{ set_ssh_keys }}\
      {{ set_nameserver }}\
      {{ set_searchdomain }}\
      {{ set_tags }}\
      {{ delete_cfg }}"
  ansible.builtin.command: >-
    pvesh create /nodes/{{ ansible_facts.hostname }}/qemu/{{ vm.key }}/config {{ to_update | trim }}
  when: to_update | trim != ''
  changed_when: true
